{% set name = "pypardiso" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/haasad/PyPardisoProject/archive/refs/tags/v0.3.1.tar.gz
  sha256: 41cb729c1fa9e69393d2f1d73f8758282f34a553ef333ad165f3fd41447518db

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<35]

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - setuptools
    - numpy
    - pip
    - "libblas =*=*mkl"  # [win]
    - mkl  # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - "libblas =*=*mkl"
    - scipy
    - mkl
    - mkl-service
    - psutil

test:
  imports:
    - pypardiso
  requires:
    - pytest
  files:
    - tests/test_basic_solve.py
    - tests/test_input_A.py
    - tests/test_scipy_aliases.py
    - tests/test_input_b.py
  commands:
    - pytest -vv tests/

about:
  home: https://github.com/cmutel/PyPardisoProject
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python interface to the Intel MKL Pardiso library to solve large sparse linear systems of equations'

extra:
  recipe-maintainers:
    - haasad
    - cmutel
